const fs = require('fs');
const { readFile } = require('fs/promises')

const fnNames = [
  "canvas",
  "surface",
  "message",
  "",
  "backingStoreRatio",
  "devicePixelRatio",
  "initialized",
  "init",
  "getElementById",
  "2d",
  "getContext",
  "viewportWidth",
  "width",
  "viewportHeight",
  "height",
  "smoothingEnable",
  "webkitBackingStorePixelRatio",
  "mozBackingStorePixelRatio",
  "msBackingStorePixelRatio",
  "oBackingStorePixelRatio",
  "backingStorePixelRatio",
  "requestAnimFrame",
  "requestAnimationFrame",
  "webkitRequestAnimationFrame",
  "mozRequestAnimationFrame",
  "oRequestAnimationFrame",
  "msRequestAnimationFrame",
  "setTimeout",
  "cancelAnimFrame",
  "cancelAnimationFrame",
  "webkitCancelAnimationFrame",
  "mozCancelAnimationFrame",
  "oCancelAnimationFrame",
  "msCancelAnimationFrame",
  "clearTimeout",
  "Your web browser does not support HTML5. Please upgrade.",
  "imageSmoothingEnabled",
  "mozImageSmoothingEnabled",
  "oImageSmoothingEnabled",
  "webkitImageSmoothingEnabled",
  "params",
  "currentHash",
  "tempCount",
  "paramCount",
  "clearParams",
  "decodeHash",
  " ",
  "replace",
  "substring",
  "hash",
  "location",
  "exec",
  "encodeHash",
  "getHash",
  "commitHash",
  "#",
  "+",
  "hasOwnProperty",
  "&",
  "=",
  "setScope",
  "setting",
  "getElementsByClassName",
  "getSelections",
  "loadDefaults",
  "length",
  "id",
  "data-default",
  "getAttribute",
  "saveSelections",
  "value",
  "data-format",
  "color",
  "charAt",
  "resetSelections",
  "tagName",
  "INPUT",
  "SELECT",
  "option",
  "getElementsByTagName",
  "selected",
  "setDefault",
  "selectIndex",
  "selectedIndex",
  "selectValue",
  "getSelectedIndex",
  "getSelectedValue",
  "infoBrowser",
  "dataBrowser",
  "searchString",
  "browser",
  "identity",
  "unknown",
  "versionLong",
  "versionOS",
  "userAgent",
  "searchVersion",
  "appVersion",
  "-1",
  "version",
  "infoOS",
  "dataOS",
  "OS",
  "mobile",
  "versionSearch",
  "vsyncCheck",
  "Firefox",
  "MozBoxSizing",
  "style",
  "body",
  "vsyncInfo",
  "Browser spoofing Firefox. VSYNC support unknown.",
  "vsync",
  "no",
  "Explorer",
  "msTransform",
  "Browser spoofing Internet Explorer. VSYNC support unknown.",
  "VSYNC is not available on the ",
  " platform.",
  "VSYNC support is untested in ",
  ".",
  "yes",
  " can't directly access VSYNC.",
  "vsyncBadOS",
  " can't access VSYNC on ",
  "vsyncMinVersion",
  "Update ",
  " to version ",
  "+ for VSYNC support.",
  "Internet Explorer supports VSYNC only up to 100Hz.",
  "Windows",
  "Your version of Windows is too old for smooth VSYNC.",
  "FireFox supports VSYNC only at 60Hz on ",
  "versionSearchString",
  "string",
  "prop",
  "subString",
  "indexOf",
  ";",
  "OPR",
  "Opera",
  " OPR",
  "Edge",
  "MSIE",
  "Trident",
  "rv",
  "vendor",
  "Apple",
  "Safari",
  "chrome",
  "Chrome",
  "opera",
  "Version",
  "BlackBerry",
  "PlayBook",
  "BB10",
  "BlackBerry 10",
  "iCab",
  "KDE",
  "Konqueror",
  "Camino",
  "Netscape",
  "AppleWebKit",
  "Generic Webkit",
  "Gecko",
  "Mozilla",
  "OmniWeb",
  "platform",
  "Win",
  "Windows NT",
  "iPhone",
  " OS",
  "iPad",
  "iPod",
  "Mac",
  "Android",
  "RIM",
  "Linux",
  "RESYNC",
  "STATUS",
  "red",
  "POOR PERFORMANCE",
  "orange",
  "HIGH CPU CONSUMPTION",
  "SYNC FAILURE",
  "UNSUPPORTED",
  "BROWSER UNKNOWN",
  "ERROR",
  "green",
  "READY*",
  "blue",
  "SYNCING",
  "PERFORMANCE WARNING",
  "STUTTER WARNING",
  "MAJOR STUTTERING",
  "BROWSER BUG",
  "frameTime",
  "frameTimePrev",
  "frameCounter",
  "timePeriodFrameStart",
  "timePeriodFrameRender",
  "timePeriodAccuracyChecker",
  "fps",
  "refreshRate",
  "refreshRateFloat",
  "refreshDisplayed",
  "jitter",
  "status",
  "pixelsPerSec",
  "pixelsPerFrame",
  "autoPPS",
  "strictSync",
  ":<br>",
  "NONE",
  "innerHTML",
  "backgroundColor",
  "updateTime",
  "now",
  "performance",
  "mozNow",
  "webkitNow",
  "getTime",
  "sync",
  "updateStatus",
  "error",
  "windowCheck",
  "innerWidth",
  "innerHeight",
  "pageXOffset",
  "pageYOffset",
  "screenLeft",
  "screenTop",
  "Waiting for browser resize to finish...",
  "Waiting for browser move to finish...",
  "Waiting for browser scroll to finish...",
  "updateRefresh",
  "fail",
  "Move all apps and browser windows to primary monitor #1.",
  "display_jitter",
  "name",
  "updateFPS",
  "abs",
  "display_fps",
  "-",
  "getDisplayableFPS",
  "round",
  "addHistoricalFPS",
  "push",
  "shift",
  "Framerate Still Syncing",
  "logFPS",
  "getAverageFPS",
  "getAverageFPSdecimal",
  "getFPSvolatilityIndex",
  "getCurrentFrequency",
  "getAveragePerformance",
  "getVarianceOfFPS",
  "getGoodSeconds",
  "getCurrentFloatRefreshRate",
  "FPS:",
  " / CPU:",
  " (",
  ",",
  ")",
  "_trackEvent",
  "updatePixelsPerSec",
  "GOOD",
  "display_pps",
  "display_ppf",
  "updatePixelsPerFrame",
  "updatePixelsPer",
  "display_refresh",
  "?",
  "onRefreshRateChange",
  "getPreferredLookbehind",
  "ignoreNextCycle",
  "accuracyCheck",
  "Initializing...",
  "Browser pause detected, resynchronizing...",
  "Browser freeze detected, resynchronizing...",
  "PERFORMANCE",
  "HIGH_CPU",
  "STUTTER_BUG",
  "BROWSERBAD",
  "BROWSERUNKNOWN",
  "SYNCFAIL",
  "STUTTER_DETECTED",
  "STUTTER_MAJOR",
  "STUTTER_CAUTION",
  "Potential browser stutter occured (",
  "Browser stutter detected (",
  "+). Close other apps and tabs.",
  "Browser stuttering is occuring (",
  "HARD",
  "beginMeasuring",
  "Framerate Strange",
  "Unusual stuttering detected, resynchronizing...",
  "Low Framerate. Try closing all apps and browser tabs.",
  "Unable to VSYNC. Try closing all apps and browser tabs.",
  "Framerate Fail Poor",
  "Large framerate increase, resynchronizing...",
  " to ",
  "Large framerate decrease, resynchronizing...",
  "Browser framerate varying too much. Close other apps and tabs.",
  "Try closing apps/browser tabs. Verify chrome://gpu status.",
  "Try closing apps/tabs. Verify GPU acceleration is enabled.",
  "Framerate Performance Low",
  " VSYNC non-synchronization bug. Restart browser.",
  "Too fast. Please enable VSYNC in chrome://flags",
  "Too fast. VSYNC may be disabled in your browser.",
  "Low frame rate. Try closing all apps and browser tabs.",
  "<i><span style='font-size: 20px;'>NOTE: Internet Explorer does not run 120fps on 120Hz monitors.</span></i>",
  "<i><span style='font-size: 20px;'>NOTE: Edge does not run 120fps on 120Hz monitors.</span></i>",
  "<i><span style='font-size: 20px;'>NOTE: iPad Safari does not currently support 120Hz yet. See <a href='https://bugs.webkit.org/show_bug.cgi?id=173434'>BugZilla report</a>.</span></i>",
  "Framerate Recovered",
  "Framerate Success",
  "countCycle",
  "createSurface",
  "createElement",
  "setDimensions",
  "bitmapToSurface",
  "drawImage",
  "replaceColor",
  "getImageData",
  "data",
  "putImageData",
  "PURSUIT_TRACK_COLOR_BACKGROUND",
  "#000000",
  "PURSUIT_TRACK_COLOR_TICKS",
  "#FFFFFF",
  "PURSUIT_TRACK_COLOR_LINES",
  "PURSUIT_TRACK_TICK_COUNT",
  "PURSUIT_TRACK_TICK_HEIGHT",
  "PURSUIT_TRACK_TICK_WIDTH",
  "PURSUIT_TRACK_HEIGHT",
  "pursuitTrack",
  "fillStyle",
  "fillRect",
  "repeat",
  "createPattern",
  "save",
  "translate",
  "restore",
  "PURSUIT_GRID_TICK_COUNT",
  "PURSUIT_GRID_TICK_HEIGHT",
  "PURSUIT_GRID_TICK_WIDTH",
  "pursuitGrid",
  "globalAlpha",
  "font",
  "bold 24px Verdana",
  "textAlign",
  "left",
  "measureText",
  "fillText",
  "0",
  "blendColor",
  "addColor",
  "min",
  "invertColor",
  "gammaColor",
  "pow",
  "setColorLuminance",
  "substr",
  "max",
  "00",
  "setPreferredHeight",
  "getPreferredHeight",
  "getWidth",
  "getHeight",
  "isMaximized",
  "outerWidth",
  "outerHeight",
  "isFullScreen",
  "goFullScreen",
  "requestFullscreen",
  "documentElement",
  "mozRequestFullScreen",
  "webkitRequestFullScreen",
  "msRequestFullscreen",
  "exitFullScreen",
  "cancelFullscreen",
  "mozCancelFullScreen",
  "webkitCancelFullScreen",
  "msExitFullscreen",
  "toggleFullScreen",
  "isZoomed",
  "goZoom",
  "scrollTo",
  "overflow",
  "hidden",
  "scroll",
  "visibility",
  "position",
  "fixed",
  "exitZoom",
  "visible",
  "static",
  "toggleZoom",
  "isEmbedded",
  "goEmbed",
  "exitEmbed",
  "reset",
  "add",
  "calc",
  "cut",
  "Change in Hz detected ",
  "toFixed",
  "->",
  "validate",
  "Hz=",
  "&times;",
  " samples  ",
  "  dpr=",
  "  cores=",
  "hardwareConcurrency",
  "drift=[",
  "..",
  "]",
  "excessive drift",
  "snap",
  "vso",
  "ms",
  "tvsync"
];

async function content(path) {
  return await readFile(path, 'utf8')
}

async function main() {
  const text = await content('./frameratescopy.html');
  let rs = text;
  for (let index = 0; index < fnNames.length; index++) {
    const fnName = fnNames[index];
    if(fnName.indexOf('\'') > -1) {
      rs = rs.replaceAll(`fnNames[${index}]`, `"${fnName}"`)

    } else {
      rs = rs.replaceAll(`fnNames[${index}]`, `'${fnName}'`)
    }
  }

  try {
    fs.writeFileSync('./framerates.html', rs);
    // file written successfully
  } catch (err) {
    console.error(err);
  }
}
main();
